version: "3"
services:
  nginx:
    ports:
      - "5000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=thiernos
      - MONGO_PASSWORD=mypassword

    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thiernos
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
